# FROM flink:2.2.0-scala_2.12-java17
FROM flink:1.20.3-scala_2.12-java17



COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

USER flink

WORKDIR /opt/pyflink
COPY pyproject.toml pyproject.toml
COPY README.md README.md
RUN uv python install 3.12 && uv sync
ENV PATH="/opt/pyflink/.venv/bin:$PATH"

# Download apache-flink libraries
WORKDIR /opt/flink/lib
# RUN wget https://repo1.maven.org/maven2/org/apache/flink/flink-json/2.2.0/flink-json-2.2.0.jar; \
#     wget https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/4.0.0-2.0/flink-sql-connector-kafka-4.0.0-2.0.jar; \
#     wget https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc-core/4.0.0-2.0/flink-connector-jdbc-core-4.0.0-2.0.jar; \
#     wget https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc-postgres/4.0.0-2.0/flink-connector-jdbc-postgres-4.0.0-2.0.jar; \
#     wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar

RUN wget https://repo1.maven.org/maven2/org/apache/flink/flink-json/1.20.3/flink-json-1.20.3.jar; \
    wget https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.4.0-1.20/flink-sql-connector-kafka-3.4.0-1.20.jar; \
    wget https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc-core/3.3.0-1.20/flink-connector-jdbc-core-3.3.0-1.20.jar; \
    wget https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc-postgres/3.3.0-1.20/flink-connector-jdbc-postgres-3.3.0-1.20.jar; \
    wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar

COPY --chown=flink:flink flink-config.yaml /opt/flink/conf/config.yaml
WORKDIR /opt/flink