[project]
name = "streaming"
version = "0.1.0"
description = "Data Engineering Zoomcamp — Module 7: Streaming"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-flink==2.2.0",
    "hatchling>=1.29.0",
    "kafka-python>=2.3.0",
    "setuptools",
    "sqlalchemy",
    "psycopg2-binary",
]

[tool.uv.extra-build-dependencies]
apache-beam = ["setuptools"]

[tool.hatch.build.targets.wheel]
packages = ["src/streaming"]

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"
